/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.servidorudp;

import java.awt.Dimension;
import java.awt.Point;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Usuario
 */
public class AutoCliente extends javax.swing.JFrame {

    /**
     * 1=derecha 2=abajo 3=izquierda 4=arriba
     */
    int direccion;
    Point posicion;
    Cliente client;
    boolean encendido;
    Timer timer;

    /**
     * Creates new form AutoCliente
     */
    public AutoCliente() {
        initComponents();
        encendido = false;
        //gps = new GPS();
        direccion = 1;
        posicion = new Point(0, 0);
        timer = new Timer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        car = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Iniciar movimiento");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        car.setText("OO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(car)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(car)
                .addContainerGap(462, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        if (!encendido) {
            jButton1.setText("Detener Movimiento");

            timer = new Timer();
            client=new Cliente();
            encendido = !encendido;

            Dimension dimension = this.getSize();

            //gps.start()
            Thread t = new Thread(client);
        t.start();
           
            TimerTask task = new TimerTask() {
                @Override
                public void run() {
                    if (direccion == 1) {
                        if (dimension.width > posicion.x + 100) {
                            posicion.x += 25;
                        } else {
                            direccion = 2;
                        }
                    }
                    if (direccion == 2) {
                        if (dimension.height > posicion.y + 100) {
                            posicion.y += 25;
                        } else {
                            direccion = 3;
                        }
                    }
                    if (direccion == 3) {
                        if (posicion.x - 25 > 0) {
                            posicion.x -= 25;
                        } else {
                            direccion = 4;
                        }
                    }
                    if (direccion == 4) {
                        if (posicion.y - 25 > 0) {
                            posicion.y -= 25;
                        } else {
                            direccion = 1;
                        }
                    }
                    car.setLocation(posicion.x, posicion.y);
                    client.add(posicion.x,posicion.y);
                    //client.setY(posicion.y);

                }
            };
            timer.schedule(task, 0, 1000);
        } else {
            jButton1.setText("Iniciar Movimiento");
            encendido = !encendido;
            timer.cancel();
            timer.purge();
            System.out.println("Apagado");

        }


    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel car;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
